One approach to using a persistent binary to speed up subsequent startups after the first

diff --git a/vext b/vext
--- a/vext
+++ b/vext
@@ -11,21 +11,38 @@ set -eu
 mydir=$(dirname "$0")
 program="$mydir/vext.sml"
 
+local_install=
+if [ -w "$mydir" ]; then
+    if echo | sha256sum >/dev/null 2>&1 ; then
+        local_install=true;
+    else
+        echo "WARNING: sha256sum program not found" 1>&2
+    fi
+fi
+
+sml_ident=
+
 # We need one of Poly/ML, SML/NJ, or MLton. Since we're running a
 # single-file SML program as if it were a script, our order of
 # preference is based on startup speed.
 
 if [ -z "$sml" ]; then
-    if sml -h 2>&1 | grep -q 'Standard ML of New Jersey'; then
+    if [ -n "$local_install" ] && mlton 2>&1 | grep -q 'MLton'; then
+	sml="mlton"
+        sml_ident=$(mlton)
+    elif sml -h 2>&1 | grep -q 'Standard ML of New Jersey'; then
 	sml="smlnj"
+        sml_ident=$(sml -h)
     # We would prefer Poly/ML to SML/NJ, except that Poly v5.7 has a
     # nasty bug that occasionally causes it to deadlock on startup.
     # That appears to be fixed in their repo, so we could promote it
     # up the order again at some point in future
-    elif echo | poly -v 2>/dev/null | grep -q 'Poly/ML'; then
+    elif polyc --help >/dev/null && ( echo | poly -v 2>/dev/null | grep -q 'Poly/ML' ); then
 	sml="poly"
+        sml_ident=$(poly -v)
     elif mlton 2>&1 | grep -q 'MLton'; then
 	sml="mlton"
+        sml_ident=$(mlton)
     else cat 1>&2 <<EOF
 
 ERROR: No supported SML compiler or interpreter found       
@@ -55,10 +72,15 @@ EOF
     fi
 fi
 
-tmp_sml=$(mktemp /tmp/vext-XXXXXXXX.sml)
-tmp_out=$(mktemp /tmp/vext-XXXXXXXX.bin)
-
-trap 'rm -f $tmp_sml $tmp_out' 0
+if [ -n "$local_install" ]; then
+    hash=$(sha256sum "$program" | cut -c1-16)-$(echo "$sml_ident" | sha256sum | cut -c1-16)
+    gen_sml=$mydir/.vext-$hash.sml
+    gen_out=$mydir/.vext-$hash.bin
+else
+    gen_sml=$(mktemp /tmp/vext-XXXXXXXX.sml)
+    gen_out=$(mktemp /tmp/vext-XXXXXXXX.bin)
+    trap 'rm -f $gen_sml $gen_out' 0
+fi
 
 arglist=""
 for arg in "$@"; do
@@ -71,13 +93,17 @@ for arg in "$@"; do
 done
 
 case "$sml" in
-    poly) echo 'use "'"$program"'"; vext ['"$arglist"'];' |
-		poly -q --error-exit ;;
+    poly)
+        if [ ! -x "$gen_out" ]; then
+            polyc -o "$gen_out" "$program"
+        fi
+	"$gen_out" "$@" ;;
     mlton)
-	cat "$program" > "$tmp_sml"
-	echo 'val _ = main ()' >> "$tmp_sml"
-	mlton -output "$tmp_out" "$tmp_sml"
-	"$tmp_out" "$@" ;;
+        if [ ! -x "$gen_out" ]; then
+	    echo "val _ = main ()" | cat "$program" - > "$gen_sml"
+	    mlton -output "$gen_out" "$gen_sml"
+        fi
+	"$gen_out" "$@" ;;
     smlnj)
 	cat "$program" | (
 	    cat <<EOF
@@ -102,8 +128,8 @@ EOF
 val _ = vext [$arglist];
 val _ = OS.Process.exit (OS.Process.success);
 EOF
-            ) > "$tmp_sml"
-	CM_VERBOSE=false sml "$tmp_sml" ;;
+            ) > "$gen_sml"
+	CM_VERBOSE=false sml "$gen_sml" ;;
     *)
 	echo "Unknown SML implementation name: $sml";
 	exit 2 ;;
